version: '3.4'

services:
#  catalog-api:
#    build:
#      context: .
#      dockerfile: src/Catalog.API/Dockerfile
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ConnectionString=Server=sqldata;Database=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word
  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourWeak(!)Password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
 
volumes:
  pgdata: # Stores data outside the container to ensure persistence
  rabbitmq_data:
  redis_data: